### ISSUE TITLE
Missing format on item tooltips

### ISSUE THREAD

**Issue by Blizz991** [nexus-devs/wow-classic-items#11]
An extensive amount of tooltips are missing format for some of the labels.

An example would be: https://api.nexushub.co/wow-classic/v1/items/anathema-alliance/19019 (Thunderfury)
Where the following label:

> Chance on hit: Blasts your enemy with lightning, dealing 300 Nature damage and then jumping to additional nearby enemies.  Each jump reduces that victim's Nature resistance by 25. Affects 5 targets. Your primary target is also consumed by a cyclone, slowing its attack speed by 20% for 12 sec.

Is missing a format that specifies this text should be in specific format (uncommon in this case).
[![image](https://user-images.githubusercontent.com/5943291/91467675-2fea2f00-e891-11ea-931c-9dd252cdc24a.png)](https://classic.wowhead.com/item=19019/thunderfury-blessed-blade-of-the-windseeker)

There's obviously ways to guess as it after pulling from the API, but would obviously be better if it just came with the API :).

**Comment by Blizz991** [comment]
Workaround for now (just for anyone running into the same issue):

```typescript
fixMissingFormats(tooltip: Tooltip): string {
    if (!tooltip.label || tooltip.format) {
        // No format set
        return '';
    }
    if (tooltip.label.includes('Use:') ||
        tooltip.label.includes('Chance on hit:')) {
        return ' item__quality--uncommon';
    } else {
        return '';
    }
}
```

**Comment by Blizz991** [comment]
Your commit only removes empty labels, it does not fix the missing format

**Comment by Nakroma** [comment]
The Thunderfury label object is now

{"label":"Chance on hit: Blasts your enemy with lightning, dealing 300
Nature damage and then jumping to additional nearby enemies.  Each
jump reduces that victim's Nature resistance by 25. Affects 5 targets.
Your primary target is also consumed by a cyclone, slowing its attack
speed by 20% for 12 sec.","format":"Uncommon"}

Are there any labels that aren't getting catched by that commit?


Am Di., 1. Sept. 2020 um 23:54 Uhr schrieb Blizz <notifications@github.com>:

**Comment by Blizz991** [comment]
Aye, it does seem to work - I realised you hadn't pushed the change to the live api itself (works just fine after we pulled latest changes from your repository, hence why I deleted the comment - sorry for the confusion) 👍

**Comment by Nakroma** [comment]
Ah that makes sense, updating the API always takes a bit. Sorry didnt see that since I answered per mail :)
