### ISSUE TITLE
Adding Classic TBC data

### ISSUE THREAD

**Issue by kristianronningen** [nexus-devs/wow-classic-items#13]
Any chance the json files can be updated with the TBC data?
https://tbc.wowhead.com/database

**Comment by Nakroma** [comment]
That's definetly on the todo list. However quite a bit of the item desc requires the blizzard API, so we'd have to either wait for that or rewrite it to use Wowhead only

**Comment by Nakroma** [comment]
So the API is definetly coming, the question is when: https://us.forums.blizzard.com/en/blizzard/t/hey-blizzard-devs-whatcha-thinkin-bout-tbcc-apis/16476/4
