### ISSUE TITLE
Missing item: Chronoboon Displacer

### ISSUE THREAD

**Issue by mantysalo** [nexus-devs/wow-classic-items#23]
Hey, I noticed that [Chronoboon Displacer](https://tbc.wowhead.com/item=184937/chronoboon-displacer) is missing from [data/json/data.json](data/json/data.json)

Let me know if I can do something to help fix this. Thanks!

**Comment by Nakroma** [comment]
Hey, a re-build is the only thing that should be needed for this. (the item was added after the current build)
