### ISSUE TITLE
[Question] How can i retrieve the source path to the image file ?

### ISSUE THREAD

**Issue by p4535992** [nexus-devs/wow-classic-items#36]
Hi I was trying following a search for the name of the object to retrieve the link to the image from sites like Wowhead .
For example if the icon name is "inv_fabric_purplefire_o01" i want to retrieve [http://wow.zamimg.com/images/wow/icons/large/inv_fabric_purplefire_01.jpg](https://wow.zamimg.com/images/wow/icons/large/inv_fabric_purplefire_01.jpg)

Is there any way to do this ?

**Comment by p4535992** [comment]
Never,m

**Comment by Nakroma** [comment]
Hey, you can put `iconSrc: 'wowhead'` in the constructor to make the `icon` property automatically return wowhead links. If you don't want to do that for some reason you can just do `https://wow.zamimg.com/images/wow/icons/large/${item.icon}.jpg` (which is what the database class does behind the scenes)

**Comment by p4535992** [comment]
Ty very much. I will try out this week end.
